name: "SilverBullet"
description: "A workshop for the mind"
version: "0.0.5"
image: ghcr.io/wozz/ha-addons/silverbullet-{arch}
panel_icon: mdi:file-document-multiple-outline
slug: "silverbullet"
hassio_api: false
init: false
ingress: false
ports:
  "3000/tcp": 3300
arch:
  - aarch64
options: {}
schema: {}
