name: "Envoy Proxy"
description: "An SSL/TLS proxy for HomeAssistant."
version: "0.3.0"
slug: "envoy_proxy"
init: false
ports:
  443/tcp: 12443
  80/tcp: null
map:
  - "ssl"
startup: services
arch:
  - aarch64
  - armhf
  - armv7
options:
  domain: "*"
  ssl_fullchain: "fullchain.pem"
  ssl_privkey: "privkey.pem"
  ha_port: 8123
  expose_metrics: false
  redirect_http: false
schema:
  domain: "str?"
  ssl_fullchain: "str?"
  ssl_privkey: "str?"
  ha_port: "int?"
  expose_metrics: "bool?"
  redirect_http: "bool?"
