name: "Publish Envoy"

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    name: Publish Envoy Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Version
        uses: ./.github/actions/check-ghcr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: wozz/ha-addons/envoy_proxy
          configpath: envoy_proxy/config.yaml
      - name: Publish
        if: ${{ steps.check.outputs.status == '404' }}
        uses: home-assistant/builder@master
        with:
          args: |
            --aarch64 \
            --target envoy_proxy \
            --docker-hub ghcr.io/wozz/ha-addons \
            --image envoy_proxy
